services:
  reverse-proxy:
    image: traefik:v3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme.json:/acme.json
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`monsupersite.fr`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$6ydic0em$ZAhWtxDpkgZhpBOGT7ibu."
    networks:
      - web
  web:
      build: './docker-build/php/'
      volumes:
          - ./app/shop.networked-hells.com:/var/www/shop.networked-hells.com
      links:
          - db:db
      networks:
          - web
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.blog.rule=Host(`shop.networked-hells.com`)"
          - "traefik.http.routers.blog.entrypoints=websecure"
  db:
        build: './docker-build/mysql/'
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3307:3307"
        environment:
            - MYSQL_ROOT_PASSWORD=thisisapassworddamned
        networks:
            - web
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8083:80"
        links:
            - db:db
        networks:
        - web
networks:
  web:
    external: true